version: '3.6'
services:
  graphql-engine:
    image: hasura/graphql-engine:v2.14.0
    ports:
    - "8080:8080"
    restart: always
    environment:
      HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://postgres:postgres@10.2.0.5:5432/postgres
      PG_DATABASE_URL: postgres://postgres:postgres@10.2.0.5:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_DEV_MODE: "false"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_ADMIN_SECRET: "c37AtBerlin#22"
